services:
  - name: "zegotech.cn"
    endpoints:
      - url: "https://www.zegotech.cn/"
        response_regex: "备案号"
  - name: "talkline.cn"
    endpoints:
      - url: "https://talkline.cn/"
        response_regex: "备案号"
  - name: "备案号链接检测"
    endpoints:
      - url: "https://beian.miit.gov.cn"
        expected_status: 200
